config/routes.rb
Betu::Application.routes.draw do
  resources :bets

  devise_for :users
  root "pages#home" # me lleva a root_path
  get "about" => "pages#about" # me lleva a about_path

  

end

app/models/bet.rb
class Bet < ActiveRecord::Base
	belongs_to :user 

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

	
	validates :bet, presence: true
	validates :bet, length: { maximum:100 }

	validates :description, presence: true
	validates :description, length: { maximum:140 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable  
             
  has_many :bets

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @bets = Bet.all.order("Created_at DESC").paginate(:page => params[:page], :per_page => 12)
  end

  def show
  end

  def new
    @bet = current_user.bets.build
  end

  def edit
  end

  def create
    @bet = current_user.bets.build(bet_params)

      if @bet.save
        redirect_to @bet, notice: 'Bet was successfully created.'
      else
        render action: 'new'
      end
  end

  def update
      if @bet.update(bet_params)
        redirect_to @bet, notice: 'Bet was successfully updated.'
      else
        render action: 'edit'
      end
  end

  def destroy
    @bet.destroy
      redirect_to bets_url
      head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])
    end

    def correct_user
      @bet = current_user.bets.find_by(id: params[:id])
      redirect_to bets_path, notice: "Not authorized to edit this bet" if @bet.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:bet, :description, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bets/_form.html.erb
<%= form_for @bet, html: { multipart: true } do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :bet %><br>
    <%= f.text_field :bet, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render 'form' %>

<%= link_to @bet do %>
<span class="glyphicon glyphicon-eye-open"></span>
Show
<% end %> |
<%= link_to 'Back', bets_path %>

app/views/bets/index.html.erb
<div id="bets" class="transitions-enabled">

<% @bets.each do |bet| %>

  <div class="box panel panel-default">
  <%= link_to image_tag(bet.image.url(:medium)), bet %>

  <div class="panel-body">
    <h4><%= bet.bet %></h4>
    <p><%= bet.description %></p>
    <p><strong><%= bet.user.name if bet.user %></strong></p>   
    
    <% if bet.user == current_user %>

    <div class="actions">     
      
      <%= link_to edit_bet_path(bet) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>

      <%= link_to bet, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <span class="glyphicon glyphicon-trash"></span>
      Delete
      <% end %>

    </div>
    <% end %>

  </div>

  </div>

<% end %>

</div>

<div class="center">
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/bets/new.html.erb
<h1>New bet</h1>

<%= render 'form' %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<%= link_to bets_path do %>
<span class="glyphicon glyphicon-chevron-left"></span>
BACK
<% end %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			
		<div class="panel-heading center">
			<%= image_tag @bet.image.url(:medium) %>
		</div>

		<div class="panel-body">
			<h4><%= @bet.bet %></h4>
			<p><%= @bet.description %></p>
			<p><strong><%= @bet.user.name if @bet.user %></strong></p>
<% if @bet.user == current_user %>
		      <%= link_to edit_bet_path(@bet) do %>
		        <span class="glyphicon glyphicon-edit"></span>
		        Edit
		      <% end %>
			<%= link_to @bet, method: :delete, data: { confirm: 'Are you sure?' } do %>
      		<span class="glyphicon glyphicon-trash"></span>
     		 Delete
      		<% end %>
			  
<% end %>
		</div>


		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-inverse navbar-fixed-bottom">
	<div class = "container">
		<p class ="navbar-text">Site Built By Martín Mellado</p>
	</div>
</div>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45535809-1', 'bet-u.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BET-U", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Bets", bets_path %></li>
        <li><%= link_to "About", about_path %></li>
        
        <% if user_signed_in? %>


<li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"><b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to edit_user_registration_path do %><span class="glyphicon glyphicon-user"></span> Profile <% end %></li>
          <li><%= link_to new_bet_path do %><span class="glyphicon glyphicon-plus"></span> New Bet<% end %></li>
          <li class="divider"></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
 <!--  
          <li>
            <%= link_to new_bet_path do %>
            <span class="glyphicon glyphicon-plus"></span> New Bet
            <% end %>
          </li>

          <li>
            <%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-user"></span> Profile
          <% end %>
          </li>

          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
-->
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bet-U</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <meta name="google-site-verification" content="oM0B2IFbttfQ6MfukBKcRgfZ3_oMzlHNEkaK-pnlxrs" />
  
</head>
<body>

  <%= render 'layouts/header' %>

	<div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
		<%= yield %>
	</div>

  <%= render 'layouts/ga' %>
</body>
  <%= render 'layouts/footer' %>
</html>
 

app/views/pages/about.html.erb
<div class="jumbotron">	
<div class="row">
    <div class="span12">
        <h1>About us</h1>
        <p>We are working to deploy this application soon.<br> If you need more information send us an email to contact@bet-u.com<br>GIVE US YOUR FEEDBACK!</p>
    </div>
</div>

<div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'bet-u'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

    <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'bet-u'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
    </script>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to Bet-U</h1>
	
	<% if user_signed_in? %>
	
	# Yeah! you are online.
	
	<% else %>

	<p>
       <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-ms" %>
       <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-ms" %>
 	 </p>  

	<% end %>

</div>